stages:
  - install_dependencies
  - build_unit

variables:
  UNIT_TAG: "1.31.1-1"

cache:
  key: unit
  paths:
    - unit/

install_dependencies:
  stage: install_dependencies
  script:
    - apt update
    - apt install -y software-properties-common git
    - add-apt-repository -y ppa:ondrej/php
    - apt update
    - apt install -y build-essential libssl-dev libpcre2-dev
    - apt install -y libphp7.4-embed libphp8.0-embed libphp8.1-embed libphp8.2-embed

build_unit_php74:
  stage: build_unit
  script:
    - git clone https://github.com/nginx/unit.git
    - git clone https://github.com/nginx/njs
    - cd njs
    - ./configure && make
    - cd ../unit
    - git checkout tags/$UNIT_TAG -b $UNIT_TAG
    - ./configure php --module=php74 --config=/usr/lib64/php7.0/bin/php-config --lib-path=/usr/lib64/php7.0/lib64 --njs --cc-opt="-I../njs/src/ -I../njs/build/" --ld-opt="-L../njs/build/"
    - make
    - make install
  artifacts:
    paths:
      - unit/
    expire_in: 3 days

build_unit_php80:
  stage: build_unit
  script:
    - git clone https://github.com/nginx/unit.git
    - git clone https://github.com/nginx/njs
    - cd njs
    - ./configure && make
    - cd ../unit
    - git checkout tags/$UNIT_TAG -b $UNIT_TAG
    - ./configure php --module=php80 --config=/usr/lib64/php8.0/bin/php-config --lib-path=/usr/lib64/php8.0/lib64 --njs --cc-opt="-I../njs/src/ -I../njs/build/" --ld-opt="-L../njs/build/"
    - make
    - make install
  artifacts:
    paths:
      - unit/
    expire_in: 3 days

build_unit_php81:
  stage: build_unit
  script:
    - git clone https://github.com/nginx/unit.git
    - git clone https://github.com/nginx/njs.git
    - cd njs
    - ./configure && make
    - cd ../unit
    - git checkout tags/$UNIT_TAG -b $UNIT_TAG
    - ./configure php --module=php81 --config=/usr/lib64/php8.1/bin/php-config --lib-path=/usr/lib64/php8.1/lib64 --njs --cc-opt="-I../njs/src/ -I../njs/build/" --ld-opt="-L../njs/build/"
    - make
    - make install
  artifacts:
    paths:
      - unit/
    expire_in: 3 days

build_unit_php82:
  stage: build_unit
  script:
    - git clone https://github.com/nginx/unit.git
    - git clone https://github.com/nginx/njs.git
    - cd njs
    - ./configure && make
    - cd ../unit
    - git checkout tags/$UNIT_TAG -b $UNIT_TAG
    - ./configure php --module=php82 --config=/usr/lib64/php8.2/bin/php-config --lib-path=/usr/lib64/php8.2/lib64 --njs --cc-opt="-I../njs/src/ -I../njs/build/" --ld-opt="-L../njs/build/"
    - make
    - make install
  artifacts:
    paths:
      - unit/
    expire_in: 3 days
# Repeat for other PHP versions, adjusting the paths as necessary
# ...