name: Build NGINX Unit with PHP and NJS Support

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.4', '8.0', '8.1', '8.2'] # Add other PHP versions here if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update -qq
        sudo apt install -y software-properties-common git build-essential libssl-dev libpcre2-dev libpcre3-dev
        sudo add-apt-repository -y ppa:ondrej/php
        sudo apt-get update -qq
        sudo apt-get install -y libphp${{ matrix.php_version }}-embed

    - name: Build njs
      run: |
        git clone https://github.com/nginx/njs
        cd njs
        ./configure && make

    - name: Build NGINX Unit with PHP ${{ matrix.php_version }} and NJS support
      run: |
        cd ..
        git clone https://github.com/nginx/unit.git
        cd unit
        git checkout tags/1.30.0 -b 1.30.0
        ./configure --njs \
            --cc-opt="-I../../njs/src/ -I../../njs/build/" \
            --ld-opt="-L../../njs/build/" \
            php --module=php${{ matrix.php_version }} \
            --config=/usr/lib64/php${{ matrix.php_version }}/bin/php-config \
            --lib-path=/usr/lib64/php${{ matrix.php_version }}/lib64
        make

    - name: Install NGINX Unit
      run: |
        cd unit
        make install DESTDIR=${{ github.workspace }}/build
