name: Build NGINX Unit with PHP and NJS Support

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php_version: ['7.4', '8.0', '8.1', '8.2'] # Add other PHP versions here if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libpcre3-dev
        sudo apt-get install -y php${{ matrix.php_version }}-dev

    - name: Build njs
      run: |
        git clone https://github.com/nginx/njs
        cd njs
        ./configure && make

    - name: Build NGINX Unit with PHP ${{ matrix.php_version }} and NJS support
      run: |
        git clone https://github.com/nginx/unit.git
        cd unit
        git checkout tags/1.30.0 -b 1.30.0
        NJS_PATH=$(pwd)/../njs
        ./configure --njs \
                    --cc-opt="-I${NJS_PATH}/src/ -I${NJS_PATH}/build/" \
                    --ld-opt="-L${NJS_PATH}/build/"
        ./configure php --module=php${{ matrix.php_version }} \
                    --config=/usr/lib64/php${{ matrix.php_version }}/bin/php-config \
                    --lib-path=/usr/lib64/php${{ matrix.php_version }}/lib64
        make

    - name: Install NGINX Unit
      run: |
        cd unit
        make install DESTDIR=${{ github.workspace }}/build
