name: Build NGINX Unit with PHP and NJS Support

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php_version: ['7.4', '8.0', '8.1', '8.2'] # Add other PHP versions here if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update -qq
        sudo apt install -y software-properties-common git build-essential libssl-dev libpcre2-dev ca-certificates apt-transport-https debian-archive-keyring libeditline-dev libxml2-dev expect-dev lua-posix-dev libreadline-dev
        sudo add-apt-repository -y ppa:ondrej/php
        sudo apt-get update -qq
        sudo apt-get install -y libphp${{ matrix.php_version }}-embed php${{ matrix.php_version }}-dev php-dev

    - name: Create a staging directory for the package
      run: |
        export UNITTMP=$(mktemp -d -p /tmp -t unit.XXXXXX)
        mkdir -p $UNITTMP/unit-php${{ matrix.php_version }}/UBUNTU
        cd $UNITTMP

    - name: Build NGINX Unit with PHP ${{ matrix.php_version }} and NJS support
      run: |
        git clone https://github.com/nginx/njs
        cd njs
        ./configure && make
        cd ..
        git clone https://github.com/nginx/unit.git
        cd unit
        git checkout tags/1.30.0 -b 1.30.0
        ./configure --njs --cc-opt="-I../njs/build/src/ -I../njs/build/build/" --ld-opt="-L../njs/build/build/" .
        ./configure php --module=php${{ matrix.php_version }} --config=php-config
        make php${{ matrix.php_version }}
        mkdir -p $UNITTMP/unit-php${{ matrix.php_version }}/UBUNTU # Replace with actual module path
        mv build/php${{ matrix.php_version }}.unit.so $UNITTMP/unit-php${{ matrix.php_version }}/UBUNTU


    - name: Install NGINX Unit
      run: |
        cd unit
        make install DESTDIR=${{ github.workspace }}/build
