name: Build NGINX Unit with PHP Support

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 120 # Increase this as needed
    strategy:
      matrix:
        php_version: ['7.4', '8.0', '8.1', '8.2'] # Add other PHP versions here if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update -qq
        sudo apt install -y software-properties-common git build-essential libssl-dev libpcre2-dev ca-certificates apt-transport-https debian-archive-keyring
        sudo add-apt-repository -y ppa:ondrej/php
        sudo apt-get update -qq
        sudo apt-get install -y libphp${{ matrix.php_version }}-embed php${{ matrix.php_version }}-dev php${{ matrix.php_version }}

    - name: Set UNITTMP environment variable
      run: echo "UNITTMP=${{ github.workspace }}/unit_temp" >> $GITHUB_ENV

    - name: Create a staging directory for the package
      run: |
        mkdir -p $UNITTMP/unit-php${{ matrix.php_version }}/UBUNTU
        cd $UNITTMP

    - name: Build NGINX Unit with PHP ${{ matrix.php_version }} support
      run: |
        git clone https://github.com/nginx/unit.git
        cd unit
        git checkout tags/1.30.0 -b 1.30.0
        ./configure --prefix=/usr --statedir=/var/lib/unit --control=unix:/var/run/control.unit.sock --pid=/var/run/unit.pid --log=/var/log/unit.log --tmpdir=/var/tmp --user=unit --group=unit --tests --openssl --modulesdir=/usr/lib/unit/modules --libdir=/usr/lib/x86_64-linux-gnu --cc-opt='-g -O2 -fdebug-prefix-map=/data/builder/debuild/unit-1.30.0/pkg/deb/debuild/unit-1.30.0=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC'
        ./configure php --module=php${{ matrix.php_version }} --config=php-config${{ matrix.php_version }}
        make php${{ matrix.php_version }}
        ls -la build/ # List the contents of the build directory
        mkdir -p $UNITTMP/unit-php${{ matrix.php_version }}/UBUNTU
        mv build/lib/unit/modules/php${{ matrix.php_version }}.unit.so $UNITTMP/unit-php${{ matrix.php_version }}/UBUNTU



